### ISSUE TITLE
ImportError: cannot import name 'xgrammar_bindings' 

### ISSUE THREAD

**Issue by lifeiteng** [mlc-ai/xgrammar#117]
python -c "import xgrammar; print(xgrammar)"

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/xgrammar/__init__.py", line 1, in <module>
    from . import testing
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/xgrammar/testing.py", line 7, in <module>
    from .base import _core
  File "/home/lifeiteng/.local/lib/python3.10/site-packages/xgrammar/base.py", line 6, in <module>
    from . import xgrammar_bindings as _core
ImportError: cannot import name 'xgrammar_bindings' from partially initialized module 'xgrammar' (most likely due to a circular import) (/home/lifeiteng/.local/lib/python3.10/site-packages/xgrammar/__init__.py)
```

**Comment by Ubospica** [comment]
How are you building the project? There are several possible reasons
- The binding is not compiled
- The binding is not compiled under the same Python environment as the running environment (3.10 in your case)

**Comment by Ubospica** [comment]
Closing the issue since there is no update in two months. @lifeiteng feel free to reopen it if you still have question!
